date;time /usr/bin/python3.6 run_jpeg.py 0;date
date;time /usr/bin/python3.6 run_jpeg.py 5;date
date;time /usr/bin/python3.6 run_jpeg.py 10;date
date;time /usr/bin/python3.6 run_jpeg.py 15;date
date;time /usr/bin/python3.6 run_jpeg.py 20;date
date;time /usr/bin/python3.6 run_jpeg.py 25;date
date;time /usr/bin/python3.6 run_jpeg.py 30;date
date;time /usr/bin/python3.6 run_jpeg.py 35;date
date;time /usr/bin/python3.6 run_jpeg.py 40;date
date;time /usr/bin/python3.6 run_jpeg.py 45;date
date;time /usr/bin/python3.6 run_jpeg.py 50;date
date;time /usr/bin/python3.6 run_jpeg.py 55;date
date;time /usr/bin/python3.6 run_jpeg.py 60;date
date;time /usr/bin/python3.6 run_jpeg.py 65;date
date;time /usr/bin/python3.6 run_jpeg.py 70;date
date;time /usr/bin/python3.6 run_jpeg.py 75;date
date;time /usr/bin/python3.6 run_jpeg.py 80;date
date;time /usr/bin/python3.6 run_jpeg.py 85;date
date;time /usr/bin/python3.6 run_jpeg.py 90;date
date;time /usr/bin/python3.6 run_jpeg.py 95;date
date;time /usr/bin/python3.6 run_jpeg.py 100;date